/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/ユーザー/ドキュメント/GitHub/Hello_TangPrimer/ROM/al_ip/bitmaprom.v
 ** Date	:	2020 03 12
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module bitmaprom ( doa, addra, clka, rsta );

	output [8:0] doa;

	input  [15:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(9),
				.ADDR_WIDTH_A(16),
				.DATA_DEPTH_A(65536),
				.DATA_WIDTH_B(9),
				.ADDR_WIDTH_B(16),
				.DATA_DEPTH_B(65536),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../kuranado.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({9{1'b0}}),
				.dib({9{1'b0}}),
				.addra(addra),
				.addrb({16{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule